# Generated by Django 5.0.7 on 2024-10-27 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_bank_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bank',
        ),
    ]
